figuras_geometricas = ("cuadrado", "circulo", "rectangulo")
figuras_geometricas.append("triangulo")
print(figuras_geometricas)
print(figuras_geometricas[0])
print(figuras_geometricas[1])
print(figuras_geometricas[2])